# Generated by Django 2.2.16 on 2022-11-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20221108_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение приложенное к посту', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
